### ISSUE TITLE
Screen does not fit on my iPad Mini Retina (gen 3)

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#1]
![screen shot 2017-12-12 at 7 45 56 am](https://user-images.githubusercontent.com/29305608/33893747-178b4f48-df11-11e7-9d5d-215a97058724.png)

**Comment by TeamGleasonDev** [comment]
Fits on an iPad Pro 12".

**Comment by danieltskv** [comment]
This also relates to #8 (Consider expanding UI swipe area). Before making any changes, i'll review other UI layouts.
