### ISSUE TITLE
Consider making six key beckerboard (explicit letter selection, not prediction) layout default

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#10]
Separating two issues -- looking into the prediction dictionary and changing the default layout from one that requires prediction (single swipe) to one that explicitly specifies letters (double swipe).

This reduces the learning curve of the app because:

 * Double swipe is the 'norm' in non-electronic beckerboards
 * Proper nouns (e.g. names) and infrequent (not in the 5k or 10k word list) words don't have to be added to the dictionary

Once people are familiar and comfortable with using an iPhone as a swipe speaking assistant, then we can introduce them to the deeper concept of using prediction to reduce the number of interactions needed to spell words.

**Comment by danieltskv** [comment]
OK, I've already pushed this code to the current `develop` branch. I'll release a version when i'm finished with other issues.
