### ISSUE TITLE
Not hearing TTS on iPhone 7+ running 11.1

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#3]
My iPhone TTS isn't working, I hear beeps but no speech.

Not having this trouble on iPad Pro 12" running 11.1.2.

**Comment by TeamGleasonDev** [comment]
No TTS on iPad Mini Gen 3 running 11.1.2.

**Comment by TeamGleasonDev** [comment]
Not working on iPhone 8 with 11.2.

**Comment by TeamGleasonDev** [comment]
Continues to work on iPad Pro after 11.2 upgrade.

**Comment by danieltskv** [comment]
@JayBeavers I'm trying to find out why this happens. Can it be that the silent switch is on? If the iPad doesn't have a hardware switch, try un-toggling silent mode from the control center by swiping up from the button.

Also, are there other changes from the working device, such as internet connectivity?

**Comment by TeamGleasonDev** [comment]
I'll investigate more on my devices.

**Comment by JayBeavers** [comment]
Phone was on silent mode with the physical switch on the side.
