### ISSUE TITLE
Long delay in initial screen paint

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#5]
When the app is first started, it pauses with a partially updated screen for about two seconds.

**Comment by danieltskv** [comment]
Yes, that's the static launch screen to be shown until the app fully loads. Should I created a different launch screen, for example a white screen with a logo and the app's name?

**Comment by TeamGleasonDev** [comment]
Is there a way to get a more consistent initial paint or to simply offload some of the initial UI blocking loading logic?

**Comment by danieltskv** [comment]
The app doesn't have much going on when launching. I've made it slightly more efficient by offloading the word list import to a background thread.
I'll change the launch screen to be more static with the logo and text.
