### ISSUE TITLE
Six key layout for single swipe different from six key layout for double swipe

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#7]
Double swipe six key uses a 3x2 grid whereas single swipe six key uses a sparse 3x3 grid.  These should use consistent visual layouts.

**Comment by danieltskv** [comment]
@JayBeavers In your opinion, what would be the better layout between the two?

**Comment by TeamGleasonDev** [comment]
3x2 grid

**Comment by danieltskv** [comment]
OK, will do.

**Comment by zxybdfz** [comment]
Agree :)
