### ISSUE TITLE
Consider expanding UI swipe area

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#8]
I've had a swipe or two go off target by crossing the boundary between the lower 'swipe enabled' visual area and the upper 'click on things' visual area.  Is there a way we can shrink the upper visual area so more of the display surface becomes swippable?

**Comment by danieltskv** [comment]
I can make the margins between components smaller, but that will not give much more room, especially with smaller devices. I need to think about possible different layouts. Will update.

* Maybe put the word suggestions in one line.

**Comment by danieltskv** [comment]
@JayBeavers Or, I can make the entire view swipeable, even the upper, but clicks still will go through. Thoughts?

**Comment by zxybdfz** [comment]
Many versions ago, the entire view is swipeable (please see attachment).
The gesture has to start from keyboard though, which also makes less accidental gestures when user clicks on buttons. Shall we allow swiping from any point of the screen?

![img_9325](https://user-images.githubusercontent.com/22086981/34184522-0bead130-e4d5-11e7-9054-de3f310cbff6.PNG)
