### ISSUE TITLE
Consider supplementing 'long press' from the UX

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SwipeSpeak#9]
Will single tap suffice?  Long press is kinda like right click -- it's there but most people don't use it on a common basis.

**Comment by danieltskv** [comment]
I agree, but we still need a way to differentiate between tapping a word to hear it and tapping a word to add it to the sentence. Maybe add a small green checkmark to the right of each letter (but that can be too small). @JayBeavers @zxybdfz Ideas?

**Comment by TeamGleasonDev** [comment]
One tap highlights/speaks, second tap on highlighted word invokes/adds to sentance?

**Comment by danieltskv** [comment]
Great, will do.

**Comment by zxybdfz** [comment]
Agree :) One tap to highlight sounds great.
Just wanna confirm: supplementing means both long press and second tap will add the word to sentence? Or only second tap?

**Comment by TeamGleasonDev** [comment]
Yes both long and two tap would work.
